### ISSUE TITLE
No innovation, Pure stitching...

### ISSUE THREAD

**Issue by CoderPYfd** [zju3dv/PGSR#4]
None of the contributions are presented for the first time, and it's just a patchwork of existing jobs...
Adding warp loss directly to instant-nsr-pl can be faster and better... The geoneus is so strong that it can extremely improve the quality with a different representation like gs...

**Comment by ywcmaike** [comment]
Thank you for your interest in our work. We are sorry you do not recognize our work, such as lack of innovation and contribution. Multi-view consistency constraints (such as warping loss) are common knowledge in traditional 3D vision. Many works combine multi-view geometry and deep learning methods to achieve better performance (such as GeoNeus introduces geometric constraints on Neus and achieves better performance, but it is worth noting that its performance on dtu/tnt dataset is still not as good as our PGSR method). The key lies in how to use this multi-view geometric prior knowledge to obtain higher surface accuracy. In 3D vision, truly workable work is particularly important and more practical, such as MipSplatting (MipNeRF+GS+others), which got CVPR2024 Best Student Paper. 

Our innovation and contribution lie in that we first proposed the 3DGS+MVS+SV+ unbiased depth rendering method around the plane hypothesis, which is better than all existing open-source sdf-based and gs-based methods. We have established a stronger baseline to promote the development of the 3D reconstruction field.

We are very happy to hear that you have new results and conclusions in 3D reconstruction. Please show them so that we can learn and discuss with the entire community to further promote the development of 3D reconstruction. We also want to see your completely novel work, please share it for us to read.
Criticism is easy, but execution is often pale and weak. Talk is cheap. Show me the code.

**Comment by boxaio** [comment]
well, stitcher's work is also a work. Beating existing baselines to certain extent is also a work. But innovation favors something that has rarely been done before. On neural surface reconstruction, why do we confine ourselves to Gaussian points for 3d representation, just beacuse they are efficient? What about the downstream applications?
